variables:
  - group: VisualTests

trigger: none

jobs:
- job : Run_Playwright_Tests
  displayName: 'Run Playwright Tests'
  pool:
    vmImage: ubuntu-latest
  container: mcr.microsoft.com/playwright:v1.52.0-noble
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18'
    displayName: 'Install Node.js'
  - script: npm ci
    displayName: 'npm ci'
  - script: xvfb-run npx playwright test --config=playwright.service.config.ts
    displayName: "Run Playwright Tests"
    continueOnError: true
    env:
      CLIENT_SECRET: $(CLIENT_SECRET)
      PLAYWRIGHT_SERVICE_ACCESS_TOKEN: $(PLAYWRIGHT_SERVICE_ACCESS_TOKEN)
  - task: PublishTestResults@2
    displayName: 'Publish test results'
    inputs:
      searchFolder: 'test-results'
      testResultsFormat: 'JUnit'
      testResultsFiles: 'results.xml'
      mergeTestResults: false
      failTaskOnFailedTests: true
      testRunTitle: 'Power BI Tests'
    condition: succeededOrFailed()