variables:
  - group: VisualTests

trigger: none  # No CI triggers

schedules:
  - cron: "0 */6 * * *"
    displayName: "Run every 6 hours"
    always: true   # Ensures the pipeline runs even if there are no code changes
    branches:
      include:
        - main      # Replace with your branch name if different

jobs:
- job : Run_Playwright_Tests
  displayName: 'Run Playwright Tests'
  pool:
    vmImage: ubuntu-latest
  container: mcr.microsoft.com/playwright:v1.48.2-jammy
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18'
    displayName: 'Install Node.js'
  - script: npm ci
    displayName: 'npm ci'
  - script: xvfb-run npx playwright test --config=playwright.config.v1.ts
    displayName: "Run Playwright Tests"
    continueOnError: true
    env:
      CLIENT_SECRET: $(CLIENT_SECRET)
  - task: PublishTestResults@2
    displayName: 'Publish test results'
    inputs:
      searchFolder: 'test-results'
      testResultsFormat: 'JUnit'
      testResultsFiles: 'results.xml'
      mergeTestResults: false
      failTaskOnFailedTests: true
      testRunTitle: 'Power BI Tests'
    condition: succeededOrFailed()
